### ISSUE TITLE
Should all the qualifiers be type-specific?

### ISSUE THREAD

**Issue by tgamblin** [package-url/purl-spec#10]
The current spec defines `purl` qualifiers as:

> **qualifiers:** extra qualifying data for a package such as an OS, architecture, a distro, etc. Optional and type-specific.

Should all of those be type-specific?  Architectures and OS distro names/versions seem like things that should have standard names across different `purl`s, and it may become very confusing to, say, query different purls if these are defined differently across them.  Incidentally, we do include these types of things  in Spack specs.

If there are standard/reserved qualifiers, how do the names become standardized?

**Comment by pombredanne** [comment]
@tgamblin excellent point (and quite rightly as I am sure that you have been exploring the space across the board with spack)

So some qualifiers are defined for all types in https://github.com/package-url/purl-spec/tree/a21a9ecbab171fe06d1ac88843bc3721a42dbed0#known-qualifiers-keyvalue-pairs

But this is in contradiction to the snippet you pasted above that should be updated:

> qualifiers: extra qualifying data for a package such as an OS, architecture, a distro, etc. Optional and type-specific.

So the names become standardized in this section: https://github.com/package-url/purl-spec/tree/a21a9ecbab171fe06d1ac88843bc3721a42dbed0#known-qualifiers-keyvalue-pairs

If you can come with an updated and improved section that would be truly awesome!

**Comment by pombredanne** [comment]
@tgamblin anything else here: e.g. a few qualifiers have well defined names valid across all types and otherwise they are type-specific and unbounded... I can add that clarification to the spec alright

**Comment by tgamblin** [comment]
sounds good!

**Comment by pombredanne** [comment]
@tgamblin btw you input is much welcomed on #31 !
(and it was great to meet at FOSDEM)
The more I think of the problems you solve with spack, especially the intersection of things such as Python and native code and system packages, the more I feel that a pulr maqy help in the future :P

**Comment by pombredanne** [comment]
@tgamblin at thsis stage we have evolved a few common qualifiers, so I think your valid concern has been addressed alright.
It would be awesome to have a `spack` package type. Do you care to submit a small PR? do you want me to handle it instead?

**Comment by tgamblin** [comment]
@pombredanne: sorry I missed this.  I don't have the cycles to make a spack package type, but I would be happy to review one.
