### ISSUE TITLE
implementation in PHP

### ISSUE THREAD

**Issue by jkowalleck** [package-url/purl-spec#100]
hello @stevespringett

i am currently working on an implementation in PHP.

would you be so kind and create a repository for it, so i can open a PullRequest to it,
as soon as i am done?

**Comment by stevespringett** [comment]
Thanks @jkowalleck. https://github.com/package-url/packageurl-php created. All official implementations leverage the MIT license. If you're ok with that, then PRs are greatly appreciated.
