### ISSUE TITLE
PURL type for SPDX packages

### ISSUE THREAD

**Issue by sschuberth** [package-url/purl-spec#101]
I'm wondering whether it would make sense to have a PURL type for SPDX packages, so PURLs could point to SPDX packages in a similar was as SPDX [external document references](https://spdx.github.io/spdx-spec/2-document-creation-information/#26-external-document-references) do. Any comments @pombredanne @goneall @stevespringett?

**Comment by stevespringett** [comment]
What use case would this achieve that cannot be done today simply by using URI/URL to SPDX documents?

Per the README:

> A purl is a URL string used to identify and locate a software package in a mostly universal and uniform way across programing languages, package managers, packaging conventions, tools, APIs and databases.

* Do SPDX documents have their own identity?
* How would I __identify__ an SPDX document? 
* How would I __locate__ an SPDX document?

Besides these questions... Some issues I see are:
* If we support SPDX, we would also have to support CycloneDX and future SBOM formats
* Each SPDX version would have to be a unique PURL type. Same for other SBOM formats. Especially for formats with breaking changes (e.g. SPDX 1.0, 2.0, and 3.0)
* SPDX isn't a package. It can be an artifact of a package, but isn't a package by itself.

**Comment by grv87** [comment]
I agree with @stevespringett.

The problem is built-in into SPDX specification:

> Although **it is not required**, the URI **can** be constructed in a way which provides information on how the SPDX document can be found

And it is the same problem as with XML or JSON schemas and any other generic URIs. You need an actual URL to locate the package.

**Comment by grv87** [comment]
But, there is another approach: forget about SPDX [external document references](https://spdx.github.io/spdx-spec/2-document-creation-information/#26-external-document-references) and just use the URL pointing out to SPDX document.
If that document has [Package Information](https://spdx.github.io/spdx-spec/3-package-information/) section then it may be considered as a package. Actually, such SPDX document serves as a wrapper for an actual package.
But, again, this SPDX document should not contain any unresolved external references, or purl client won't be able to process it.

**Comment by grv87** [comment]
> Each SPDX version would have to be a unique PURL type

No need. Version is specified inside the document.

**Comment by sschuberth** [comment]
Thanks all for your input: I agree to what was said, in particular:

> If we support SPDX, we would also have to support CycloneDX and future SBOM formats

> And this is SPDX who should use purl, not the other way around.

So I'm closing this.
