### ISSUE TITLE
Examples of vcs_url usage should follow the spec

### ISSUE THREAD

**Issue by magnusbaeck** [package-url/purl-spec#104]
The definition of the `vcs_url` qualifier says that the value should follow the [SPDX download specification](https://github.com/spdx/spdx-spec/blob/cfa1b9d08903/chapters/3-package-information.md#37-package-download-location), but one of the examples of this qualifier doesn't follow that specification. Specifically, the generic type gives

    pkg:generic/bitwarderl?vcs_url=https://git.fsfe.org/dxtr/bitwarderl@cc55108da32

as an example but the URL would have to be git+https://git.fsfe.org/dxtr/bitwarderl@cc55108da32 to be compliant.

(I can supply a PR once #102 is merged.)

**Comment by pombredanne** [comment]
@magnusbaeck thank you! you have eagle eyes!
