### ISSUE TITLE
Support for pypi vcs components

### ISSUE THREAD

**Issue by kakumara** [package-url/purl-spec#147]
pip includes support for referencing components using a vcs. https://pip.pypa.io/en/stable/topics/vcs-support/ 

As far as I see, I cannot see purl-spec support for vcs urls in `pypi` . Is this something that needs extending?

**Comment by stevespringett** [comment]
I think the `github` or `bitbucket` purl types would likely cover these cases.

there's also the `generic` type along with `vcs_url` qualifier that could be used if those do not work.

**Comment by kakumara** [comment]
> I think the github or bitbucket purl types would likely cover these cases.

Fair enough :+1:
