### ISSUE TITLE
Reuse Subresource Integrity spec for checksums

### ISSUE THREAD

**Issue by jackfirth** [package-url/purl-spec#17]
The current `checksum` qualifier acts as an algorithm agnostic way to specify the exact representation that should be retrieved for a package, ensuring the PURL refers to a truly immutable revision of a package. But the `alg:hex` format doesn't really say what `alg` values are allowed, whether there are length limitations, how case sensitivity is handled, or whether known-broken algorithms should be disallowed even by intermediaries, and it uses hex-encoding instead of the more space-efficient base64 encoding preferred for URI-embedded binary data.

You could instead reuse the existing [Subresource Integrity](https://www.w3.org/TR/SRI/) spec, which is designed to solve all of these sorts of problems for exactly this sort of use case. If that sounds reasonable, renaming the qualifier to `integrity` instead of `checksum` might be appropriate.

**Comment by pombredanne** [comment]
@jackfirth You are so resourceful!
Would you care for a PR for this?

**Comment by jackfirth** [comment]
I work for Google so contributing technical IP would require that the spec has a FOSS license (preferably Apache 2.0) attached, an `AUTHORS` file, and that you're okay with my patches being copyright-Google instead of copyright-me. See [this gist](https://gist.github.com/jackfirth/91973ed588077f59f1dcd96e0e10ec46) I wrote for more detail.

**Comment by pombredanne** [comment]
@jackfirth ok :) the spec is dedicated to the public domain. We could make it also CC0 as an alternative for countries that do not have such concept such as Germany. Tools are MIT-licensed. We use the DCO https://developercertificate.org/ and we can make this clear.
There is no AUTHORS file and we can add an AUTHORS section to the spec itself 

I would assume this meets the Google standards @sillsm would this work out for you? 

Note also that the latest GH TOS state a default license for contributions https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license  and that the spec has a minimalist public domain dedication here https://github.com/package-url/purl-spec/blob/d31af66785896bd42dd9467b14bf9352f8f1abfe/README.rst#license

**Comment by pombredanne** [comment]
@jackfirth FYI see also #21

**Comment by jackfirth** [comment]
"Public domain" and the CC0 are explicitly disallowed by Google legal. "Copyright" has an international agreement around it's definition (Berne Convention) but "public domain" doesn't, and even in the U.S. it isn't broadly accepted that intellectual property rights are something you can "release" so the CC0 doesn't really mean anything. I cannot contribute to a CC0-license project.

I recommend Apache 2.0. You will need the explicit permission of everyone who has sent any patches contributing to the spec. GitHub's TOS only says contributions have the same license as the project they contribute to otherwise, it doesn't add a default license to each *project*. This project never had a license, so everyone's previous contributions are similarly licenseless.

**Comment by pombredanne** [comment]
@jackfirth since the licensing has been clarified, is the topic here still something you might want to contribute something?

**Comment by pombredanne** [comment]
@jackfirth I am closing this for now for lack of activity. Please reopen if you feel strongly about it!
