### ISSUE TITLE
missing namespace in the examples of rpm section from PURL-TYPES.rst

### ISSUE THREAD

**Issue by sify21** [package-url/purl-spec#195]
`pkg:rpm/centerim@4.22.10-1.el6?arch=i686&epoch=1&distro=fedora-25`
I guess namespace `fedora` is missing here, or is namespace optional?

**Comment by johnmhoran** [comment]
Hello @sify21 .  The `namespace` component is optional.  See:

- The [core-spec](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#package-url-specification-v10x) provides that `namespace` is optional -- "namespace: some name prefix such as a Maven groupid, a Docker image owner, a GitHub user or organization. Optional and type-specific."
- The `rpm` [type spec](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#rpm) includes two examples, the second with no namespace (and both of which use the `distro` qualifier to identify `fedora-25`): 

  ```
  pkg:rpm/fedora/curl@7.50.3-1.fc25?arch=i386&distro=fedora-25
  pkg:rpm/centerim@4.22.10-1.el6?arch=i686&epoch=1&distro=fedora-25
  ```

**Comment by johnmhoran** [comment]
If this ^ is inaccurate or incomplete, please chime in here so we can update the core spec as needed.

**Comment by johnmhoran** [comment]
@sify21 Thanks for opening this issue.  If my response above answers your question, please feel free to close this issue.
