### ISSUE TITLE
Using a non-default repository with cargo

### ISSUE THREAD

**Issue by ctron** [package-url/purl-spec#215]
In the documentation is says:

> - The default repository is `https://crates.io/`

But what if one doesn't use the default repository (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-other-registries)? Or what if one uses a git (or file) dependency using cargo (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)?

**Comment by bureado** [comment]
Would the repository_url qualifier satisfy this?

**Comment by ctron** [comment]
I guess so.

**Comment by johnmhoran** [comment]
Hello @ctron .  Thank you for opening this issue.  If @bureado 's reply above addresses your question, please feel free to close this issue.
