### ISSUE TITLE
Spec and Maven Rebuilds

### ISSUE THREAD

**Issue by rnc** [package-url/purl-spec#24]
A few questions:

1. Does the specification allow for specifying the location of the source repository? What happens if the source repository has been cloned from the original upstream and built from the clone? 
2. Does the specification handle the scenario where the upstream version has been rebuilt and reversioned (as is common in the case of Maven builds and being released to a company repository). Which version should be specified - the upstream version or the released version?

**Comment by pombredanne** [comment]
@rnc Thank you for chiming in!
Yes, the spec will allow to point to source repos optionally, including a cloned, forked or any place using a `qualifiers` key/value pair, for instance:

- `generic:bitwarderl?vcs_url=https://git.fsfe.org/dxtr/bitwarderl@cc55108da32042a0e385bd8e`

Or closer to your likely concern:

- `maven:org.commonjava.maven.ext/pom-manipulation-parent@2.13-SNAPSHOT?vcs_url=https://github.com/release-engineering/pom-manipulation-ext.git@42297aa55bb39b73bb2950cd47fb8b5a0f51a526`

**Comment by pombredanne** [comment]
> Does the specification handle the scenario where the upstream version has been rebuilt and reversioned (as is common in the case of Maven builds and being released to a company repository). Which version should be specified - the upstream version or the released version?

IMHO, that's to be decided on case by case: but normally the `purl`should reflect the version of the "artifact", using maven-speak, that it is pointing to. It does not make sense to use any other versio,
This version scheme of your rebuilt package may be colliding with the standard package, so to make it clearly unique you can either use the `vcs_url` qualifier as above OR use the `repository_url` or `download_url` qualifier to point to your private company repo instead. In these cases, you are sure to have a clearly identifier package as long as you provide clear, fully qualified URLs.

**Comment by pombredanne** [comment]
@rnc does this address your question adn can this be closed or not?

**Comment by jdillon** [comment]
So my interpretation of the spec is that its means to provide the type of artifact and primary coordinates of the artifacts type.   It allows for additional optional key=value data to be encoded which can be uses to indicate where something comes from in more detail, but the core aspect of the spec isn't to say where it comes from but what the type of the artifact is and whats is key/normalized (namespace/name/version) details are.

More succinctly its a coordinate system to identify whats something _is_ and not specifically where something _comes from_.  The later may be optionally provided though with some qualifiers, but those would be highly non-standard.

For example:

pkg:maven:foo/bar@1 represents the coordinates of a maven artifact with a groupId of foo, an artifactId of bar and a version of 1.  This doesn't in any way say where this *comes from*, but its useful to say what it *is*

You could have a non-standard PURL of pkg:maven:foo/bar@1?comes_from=http://somefile.jar.  There is some forming standard qualifier keys for this though IIUC its still a bit in flux.  But if you think of a PURL of more as a standard identifier of what something is, vs. where something comes from it may help.  The later is very specific to ecosystem/type and implementation but you are free to encode that into a qualifier if you need it, but I do not believe it can be generalized.

**Comment by pombredanne** [comment]
@jdillon you wrote:

> More succinctly its a coordinate system to identify whats something is and not specifically where something comes from. The later may be optionally provided though with some qualifiers, but those would be highly non-standard.

Or rather, it is a way to identify and locate. The default location assumption is that this is a public pakage that could be located o the public repository url for a given type (e.g. https://pypi.org for `pypi` http://repo1.maven.org/maven2/ for `maven` ... etc)

> For example:

> pkg:maven:foo/bar@1 represents the coordinates of a maven artifact with a groupId of foo, an artifactId of bar and a version of 1. This doesn't in any way say where this comes from, but its useful to say what it is

As I mentioned above the intent here is that it should come from the default public repository short of other context, which can optionally be specified as a "standard" classifier either a `repository_url` or  `download_url` 
See https://github.com/package-url/purl-spec#known-qualifiers-keyvalue-pairs

That said, when you are dealing with a combo of private and public package repositories, you are free to handle the resolution of where to locate some package the way you like.
