### ISSUE TITLE
Is "PURL" (all caps) considered an incorrect abbreviation?

### ISSUE THREAD

**Issue by joeattardi** [package-url/purl-spec#280]
All throughout the spec, the abbreviation "purl" (all lowercase) is used. I was wondering, is this intentional - is all uppercase ("PURL") or a mix ("pURL") considered incorrect when referring to a package URL?

**Comment by noqcks** [comment]
I have the same question.

I see `purl` being used. Example: https://tomalrichblog.blogspot.com/2023/12/the-naming-problem-isnt-complicated-if.html

And `PURL`. Example: https://resilientcyber.substack.com/p/whats-in-a-name

Would be great to give guidance on the correct naming usage.

**Comment by jbmaillet** [comment]
...and here is another example with all caps, from people who should know:
https://github.com/CVEProject/cve-schema/issues/173
These is the kind of pesky detail that does not help convincing decision maker that a project is serious.

**Comment by pombredanne** [comment]
> Would be great to give guidance on the correct naming usage.

IMHO we should not be pedantic about case: you can use any way you like, PURL is not case sensitive.

I like to use `PURL`, all uppercase when I mention it in writings. But when using it in code for a variable or field name, I use `purl` all lowercase. YMMV.

**Comment by johnmhoran** [comment]
Hi @joeattardi .  I'm pleased to note that on 2024-10-11, Ecma TC54-TG2 approved the use of `Package-URL` and `PURL`.  See https://github.com/Ecma-TC54/tg2/blob/main/meetings/2024-10-11.md

If this answers the question you raised, please feel free to close this issue -- and if not, please advise what remains to be addressed.  Thank you!

**Comment by joeattardi** [comment]
@johnmhoran Thanks, that looks like a definitive answer to my question - PURL is OK!
