### ISSUE TITLE
RPM considerations, and maybe for others as well

### ISSUE THREAD

**Issue by vbatts** [package-url/purl-spec#29]
It looks like some of the media references include a checksum of the final package or similar.

One thing that can be an issue for RPMs when determining an advisory is to the provenance of the sources and dependencies used in producing that binary. 
e.g. I could have a malicious gcc or glibc-static present at the time of building `rpm:fedora/curl@7.50.3-1.fc25?arch=i386&distro=fedora-25` but the rpm attributes of that package do not change.

The added difficulty of this is that for packages like RPM, the signature of the RPM may be embedded in the archive itself, so simply a checksum of the `*.rpm` is not sufficient, nor only a checksum of the cpio stream contained within as metadata like xattrs is separated from that cpio stream. 

There is something in having a way to cite the identity of the author of _that_ build, and further a way to cite the context(s) that the package was built. In this way it could be possible to cobble together a URI referencing _the_ _specific_ build of the package in question.

**Comment by brianf** [comment]
IIUC, there are similar challenges with package systems such as bower, go dep, cocoapods that essentially use Git urls as their coordinates. In those instances a commit id (e.g hash) is technically a valid version. Associating data across a range is therefore...interesting. I see this as a problem in the choices made by those package systems that is out of the hands of purl-spec.

**Comment by pombredanne** [comment]
@vbatts Hi and sorry for the late reply! Can you elaborate a bit when you say that `simply a checksum of the *.rpm is not sufficient,` ? AFAIK, yum/rpm repos use checksums alright do they?

**Comment by vbatts** [comment]
Sorry to imply that a checksum of the *.rpm is unreliable. Yum repos do
checksum and relay that repodata. Just that the internal signatures (or
lack thereof) is then immutable.
That data is namely on transfer because once installed the checksum of the
original is not preserved.

So perhaps providing a checksum is a good stop gap, and perhaps it needs
RFE to projects to preserve data like this for further comparison

**Comment by pombredanne** [comment]
@vbatts ok, I am not sure I understand the issue exactly: are you saying that you can get two RPMs .rpm files with a different checksum that were built exactly from the same code/deps/all the way and would possibly have the same signature internally? I do not know enough of RPMs internals but that sounds a possibility. But the same would apply to pretty much any package,  binary or not, unless you can abstract things alright (possibly when reproduciblebuild works all the way for things that are compiled to native) and if you can also abstract or ensure that many things such as dates, etc. are stable in archives (a topic I know you are quite familiar with if I recall your work on Docker images)  or if this exists in RPMs that the based-in signature ends up being the same.

Bu how is this a problem in these cases? two packages with essentially identical content and identical metadata that would have different checksums but the same baked-in same signatures could have different purl or the same purl IMHO depending on how your construct these: for instance you could add the signature as a `qualifiers` possibly?

**Comment by brianf** [comment]
I think in generally you'd want to refer to things using the named
coordinates unless you really only knew the hash or knew the statement
applied to -this- hash. The later case is not uncommon so everything should
be able to be qualified or identified by hash as appropriate.

**Comment by vbatts** [comment]
sorry for the delay. The issue is almost academic, so please forgive the mental exercise. 
The issue is not two rpms built with the same dependency per se, but rather the provenance of those dependencies. Common enough example of this is Centos and RHEL. They've have the same nvr, but an entirely independent buildroot provenance. 

Secondly, regarding the internal-rpm-signing, I think that issue can be forgone as rarely would a signature be added or replaced, without treating the package as a new artifact or environment.
