### ISSUE TITLE
Is this generic purl encoded correctly?

### ISSUE THREAD

**Issue by xnox** [package-url/purl-spec#304]
I am trying to use locator string, in spdx, pointing at purl, encoded as safe json

```json
          "referenceCategory": "PACKAGE_MANAGER",
          "referenceLocator": "pkg:generic/acl@2.3.2?checksum=sha256%3A5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c\u0026download_url=https%3A%2F%2Fdownload.savannah.nongnu.org%2Freleases%2Facl%2Facl-2.3.2.tar.gz",
          "referenceType": "purl"
```

Now i have lots of questions:
* is encoding `&` as `\u0026` acceptable?
* the spec says that qualifiers must be percent encoded..... but it also makes them ugly.
* is `sha256%3A` acceptable, or is it better of as `sha256:`?
* the doubly encoded download_url, is that correct? or should it be `https://download.....` ?

**Comment by xnox** [comment]
> This purl is not in the canonical form

is it a bug in package-url golang library?

```go
package main

import "fmt"
import purl "github.com/package-url/packageurl-go"


func main() {
	var q purl.Qualifiers
	q = purl.QualifiersFromMap(
		map[string]string{
			"downloadurl": "https://download.savannah.nongnu.org/releases/acl/acl-2.3.2.tar.gz",
			"checksum":"sha256:5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c"},
	)
	mypurl := purl.NewPackageURL("generic", "", "acl", "2.3.2", q, "")
	fmt.Println(mypurl)
}
```

```console
$ go run main.go
pkg:generic/acl@2.3.2?checksum=sha256%3A5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c&downloadurl=https%3A%2F%2Fdownload.savannah.nongnu.org%2Freleases%2Facl%2Facl-2.3.2.tar.gz
```

Or is there a way to produce "canonical form"?

**Comment by matt-phylum** [comment]
> is it a bug in package-url golang library?

Yes. The test suite says that `pkg:huggingface/microsoft/deberta-v3-base@559062ad13d311b87b2c455e67dcd5f1c8f65111?repository_url=https://hub-ci.huggingface.co` is canonical, but package-url/packageurl-go fails this test and outputs `pkg:huggingface/microsoft/deberta-v3-base@559062ad13d311b87b2c455e67dcd5f1c8f65111?repository_url=https://hub-ci.huggingface.co` instead.

This is actually pretty common. 5/14 implementations that I know of fail this particular test by encoding characters that are supposed to be left unencoded.
