### ISSUE TITLE
Make a versioned release and have pkg:package-url/purl-spec@1.0.0

### ISSUE THREAD

**Issue by bact** [package-url/purl-spec#319]
Does it possible to make a [release](https://github.com/package-url/purl-spec/releases/) of a versioned Package URL specification?

So a versioned spec will be available at a web URL like this:

`https://github.com/package-url/purl-spec/releases/tag/1.0`

And a Package URL of the Package URL spec itself like this:

`pkg:package-url/purl-spec@1.0.0`

This will be useful when making a reference in a standard documentation for a standard body that requires that the link should be a permalink (a URL should point to the same content, unchanged over time).

**Comment by jkowalleck** [comment]
see also: https://github.com/package-url/purl-spec/milestone/1

**Comment by jkowalleck** [comment]
duplicates https://github.com/package-url/purl-spec/issues/50

**Comment by bact** [comment]
Thank you
