### ISSUE TITLE
Parsing spec is missing the version

### ISSUE THREAD

**Issue by jgustie** [package-url/purl-spec#34]
The parsing section makes no mention of the version, I assume there should be another right split on '@' prior to the left split on ':', i.e.

> * Split the remainder once from right on '?'...
> * Split the remainder once from right on '@'
>   * The left side is the remainder
>   * Percent-decode the right side
>   * UTF-8-decode the version if needed in your programming language
>   * This is the version
> * Split the remainder once from left on ':'...

**Comment by pombredanne** [comment]
@jgustie thanks. let me reply in a few days as I am travelling just now

**Comment by pombredanne** [comment]
Good catch! I am added this with https://github.com/package-url/purl-spec/pull/31/commits/fa715a8d32daa750c0fa9e003e542729004536ee
Thanks!
If this works for you you can comment on the PR #31 and close this at your convenience.
