### ISSUE TITLE
Overlap with SWID

### ISSUE THREAD

**Issue by vbatts** [package-url/purl-spec#36]
I know there is a FAQ on this, and some further comment on grafeas about flexibility of using SWID or purl, though the efforts here are very much redundant with SWID.
Red Hat has raised the concerns around the paywall, but that doesn't negate the likes of standards. And I have heard that this barrier is currently or soon to be much lower (like orders of magnitude lower).
For the life of this project, adopters that may likely be faced with SWID requirements, it might likely be duplicate requirements

**Comment by stevespringett** [comment]
I do see some overlap with SWID, but I also think SWID is more closely tied to the installation, operation, maintenance, and destruction of software. More lifecycle focused.

I see PackageURL as more of a point-in-time specification, simpler to implement, and much more compatible with continuous delivery.

**Comment by vbatts** [comment]
CD is a part of lifecycle. That's the point, isn't it?

**Comment by pombredanne** [comment]
@vbatts I wished I could get any information of what these SWID tags are and have some data on where they are used: I never saw one in the wild.  
You think that there is overlap and that these are used: can you provide a bit more info and data on this? what would be an example of a tag string for instance? and if they are semantically similar then writing adapter may be easy enough too.

**Comment by stevespringett** [comment]
@vbatts My point with CD is that modern software isn't installed or patched, its pushed to Docker containers which can be deployed or destroyed at will. Patching and maintenance parts of the lifecycle do not exist but appear to be a large part of the SWID specification (from what I can tell from the XSD anyway). I can't find any publicly available information on how the spec supports the continuous delivery and deployment of software. It appears to support a legacy on-prem COTS model perfectly fine though. Perhaps clarification on the spec and the use-cases its designed for are behind the paywall. Don't know.

@pombredanne NIST is pushing SWID but I do not know for what purpose. The XSD is free to look at and use, but all the relevant documentation is behind a paywall. This could explain why adoption for SWID is so low. I will not be supporting SWID in the large OWASP projects I'm involved with while a paywall is still in place.

That said, OWASP, NIST, MITRE, and other agencies are attempting to come together next month to sort some of this out. https://open-security-summit.org/tracks/ciso/working-sessions/vulnerability-intelligence/

**Comment by pombredanne** [comment]
I finally found an example of SWID tag here https://helpx.adobe.com/enterprise/package/help/software-tag-implementation.html#SampleSWIDTagFiles

This happens to be an XML file and fairly different from a Package URL except for the fact that this is related to software identification in both cases. The schema is there too: https://standards.iso.org/iso/19770/-2/2008/schema.xsd

Eventually a Package URL could be used inside a SWID file alright to properly identify a software package such as npm, Maven or Pypi packages which is not covered at all by SWID. SWID are not URL (e.g. locators) too. So given a SWID tag I cannot fetch the corresponding code back from what I see.

No there is not much overlap IMHO but rather Package URLs could be used in SWID XML documents to make them better. The rest of SWID seems to be geared mostly towards the concerns and use cases of commercial software vendors with traditional proprietary licensing requirements, and this is completely out of the scope of a Package URL.

@vbatts Therefore I am closing this now. Feel free to reopen if you feel strongly about this!

**Comment by vbatts** [comment]
Fair enough. Thank you for the review

-------- Original Message --------
