### ISSUE TITLE
Default Maven Repository

### ISSUE THREAD

**Issue by jgustie** [package-url/purl-spec#42]
Currently the default `repository_url` value for `maven` is listed as "repo1.maven.org". I would propose changing this to "http://repo.maven.apache.org/maven2" to match the current [Super POM](http://maven.apache.org/ref/3.5.3/maven-model-builder/super-pom.html) definition and also to specify the full URL (so the protocol and path are not ambiguous).

**Comment by sschuberth** [comment]
Makes sense!
