### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by d-stahl-ericsson** [package-url/purl-spec#44]
The README gives three examples of Docker purl strings:

```
pkg:docker/cassandra@latest
pkg:docker/smartentry/debian@dc437cc87d10
docker:gcr.io/customer/dockerimage@sha256:244fd47e07d10
```

Unless I misunderstood the syntax, the third one appears to be a typo?

**Comment by althonos** [comment]
IMO yes, for two reasons:
- now everything is `pkg:` prefixed
- the version should be percent-encoded

So I'd go for
```
pkg:docker/gcr.io/customer/dockerimage@sha256%3A244fd47e07d10
```
