### ISSUE TITLE
Expected PURL for swift

### ISSUE THREAD

**Issue by ken-duck** [package-url/purl-spec#53]
I was trying to identify the expected PURL for swift packages, and was wondering if there was a suggested format.

My first guess is that it is likely similar (but not quite the same as) golang, as it appears that [swift packages](https://swift.org/package-manager/) require both a repository path and a package name. Since a package name is required, I suspect that the repository path is all contained within the namespace.

For example, from the examples on the linked swift package site perhaps we would have:

```
pkg:swift/github.com/apple/example-package-fisheryates/FisherYates@2.0.0
pkg:swift/github.com/apple/example-package-playingcard/PlayingCard@3.0.0
pkg:swift/github.com/apple/example-package-deckofplayingcards/DeckOfPlayingCards@3.0.0
```
Note that there is one description of a possible ways to allow multiple swift modules in one repository [here](https://github.com/ddunbar/swift-evolution/blob/multi-package-repos/proposals/NNNN-swiftpm-multi-package-repos.md). It is not official by any means, from what I can tell, but it appears that it could be supported using the `subpath` component of PURL.

Does this fulfill the expectations of the PURL for swift?

Thanks

**Comment by stevespringett** [comment]
@ken-duck, I think you've interrupted the spec correctly and applied it to swift quite well. @pombredanne This is my thoughts on swift:



swift for Swift packages

There is no default package repository: the namespace is implied from dependencies defined in Packages.swift

* The namespace and name must be lowercased
* The subpath is used to point to a subpath inside a package
* The version is a commit or tag

Examples:
```
pkg:swift/github.com/apple/example-package-fisheryates/FisherYates@2.0.0
pkg:swift/github.com/apple/example-package-playingcard/PlayingCard@3.0.0
pkg:swift/github.com/apple/example-package-playingcard/PlayingCard@7a47ec16b59e7e39827b65c1eae79d3f32a28116
```

**Comment by stevespringett** [comment]
@jdillon I was really hoping this would be pointed out. I wanted to draw attention to the golang requirement that the namespace and name be lowercase since @ken-duck referenced it. In golang, the modules are lowercase, but the examples also point to external sites, like GitHub, similar to how we're doing swift.

I do not think swift should be lowercased due to uncertainty of the target site being referenced in the namespace is case-sensitive or not. For example, Github is case aware, not case sensitive. So case doesn't matter much, but if another provider was referenced, then that provider may be case sensitive.

-----
swift for Swift packages

There is no default package repository: the namespace is implied from dependencies defined in Packages.swift

* The subpath is used to point to a subpath inside a package
* The version is a commit or tag

Examples:
```
pkg:swift/github.com/apple/example-package-fisheryates/FisherYates@2.0.0
pkg:swift/github.com/apple/example-package-playingcard/PlayingCard@3.0.0
pkg:swift/github.com/apple/example-package-playingcard/PlayingCard@7a47ec16b59e7e39827b65c1eae79d3f32a28116
```

We may want to consider removing this requirement from golang as well.

**Comment by jdillon** [comment]
In terms of DNS names, like github.com only that portion could potentially be considered insensitive, everything else totally depends on the server implementation.  Github for example treats these the same:
* https://github.com/APPLE
* https://github.com/apple

But another service may not.

I think this again falls into the section of leave it as given; as the more per-type transformations to normalize imply more chances that any given time any "spec compliant impl" may be wrong if some new format gets introduced with new transformation rules.

Related to: https://github.com/package-url/purl-spec/issues/38

I also suggest that if some format has some requirement saying name or namespace is lowercase or uppercase or whatever, that the purl spec shouldn't care about that either; and a user configures a purl for one of those types with invalid case, then the purl just is invalid in terms of that specific ecosytem, but in terms of the general purl specification is valid.

IMO there should be *zero* type-specific transformations.  Only generic applicable to *all* normalizations.  And I think wrt to case, the only field that can be mutated like this is the type.  Everything else is going to be very ecosystem specific and IMO its not possible or reasonable to implement a proper spec compliant implementation that could ever be spec-valid with these sorts of transformations.

**Comment by ken-duck** [comment]
My question was answered satisfactorily, and it looks like discussion has ended. Thanks for the help!
