### ISSUE TITLE
Add Sonatype OSS as adopter 

### ISSUE THREAD

**Issue by sbs2001** [package-url/purl-spec#74]
https://ossindex.sonatype.org/doc/coordinates here they clearly mention they use purl . By the way this implies the whole Nexus platform is using purl is some way or another. 

Definitely add this in our README

**Comment by stevespringett** [comment]
Correct. OSS Index supports it as does Nexus IQ (part of Nexus Lifecycle)

**Comment by brianf** [comment]
I'll make the addition

**Comment by pombredanne** [comment]
:+1:
