### ISSUE TITLE
Thoughts on handling NPM local path dependencies

### ISSUE THREAD

**Issue by athos-ribeiro** [package-url/purl-spec#89]
As the title says, npm 2.0.0 added support for local paths (See https://docs.npmjs.com/files/package.json#local-paths).

How could such package be expressed?

The package does have a name, but it is located in the path of another package.

Would using a PURL in the `download_url` qualifier to point to the package owning the file, and then using a `file_name` qualifier to point to the proper file make sense? This would have terrible readability, but I do not see another way out of this one.

My major concern on this is: are there any drawbacks on using a purl as a download_url qualifier?

**Comment by iamwillbar** [comment]
This is an interesting problem @athos-ribeiro. Local paths are usually used for local testing and aren't intended to be published to public registries and they can be absolute or relative and don't need to be within the package itself. This means that the location could point at completely different content depending on the state of the environment where you resolve the purl and the identity would dependent entirely on the content that is at that location once you resolve it (you and I could have completely different packages in that local path). Those limitations indicate that this might be something outside of the scope of purl. 

If this is still something you'd like to solve it would be useful to understand more about the use cases where a purl representing a local path would be used. In the meantime I'll go ahead and close this issue but feel free to re-open with that additional information.
